### PR TITLE
Providing a newly updated list and new file including 7169 sentences. Thanks to Wikipedia and Python.

### PR DESCRIPTION
**Pull request by 0xdolan**
Providing a newly updated list and new file including 7169 sentences. Thanks to Wikipedia and Python.

### CODE REVIEW

**Comment by layik** [comment]
Great kake Dolan. Would you like to dive into WordNet and make it KurdiNet? The citation is in the tweet thread. 

Awesome work in any case!

**Comment by 0xdolan** [comment]
Thanks, Dr. gyan.
How come? It's not clear to me!

**Comment by layik** [comment]
So, there is definitely some effort from Sinna, they have created a WordNet called KurdiNet, but I could not find it for you. So it might be a very good followup paper to be published somewhere, if you can manage to get something built which is "open source" so that people don't have to do this again. 

It might be something basic but if we publish the script/data, it might be novel and worth publishing. I am happy to do the writeup/publication if you do the development :)

**Comment by layik** [comment]
https://github.com/sinaahmadi/KurdishPOSTagger

**Comment by layik** [comment]
https://github.com/sinaahmadi might well be miles ahead already.

**Comment by 0xdolan** [comment]
Ok! For sure I will check it out. It seems it doesn’t updated for 1 year! I will try my best. Frankly, I have started working on a project like this one month ago but didn’t have much time to work on it but I will try to merge this two to one! It is a great step ahead for kurdish language. Isn’t it?

**Pull request merged**
