### PR TITLE
add missing character in frequency chat 'وو'

### PR DESCRIPTION
**Pull request by 0xdolan**
a character mistakenly missed when generating the chart, so the chart redesigned again including the missed character (وو). :-)
a txt file of the frequencies also added.

### CODE REVIEW

**Comment by layik** [comment]
kake @dolanskurd gyan dest khosh!

Let me have the Python code please, as I think that is what you used to generate the chart? Otherwise I will add some R code which will be better, our `https://raw.githubusercontent.com/layik/kurdi/master/corpus/letters_lines.txt` contains وو

Also, avoid including text file with frequencies, better in data science terms. So again, let me have the Python code and I will embed it in the README to auto-update as word-list is updated rather than hardocde png's and PDF's.

I hope that is clear.

**Comment by 0xdolan** [comment]
Sure 🙏🏻

**Comment by layik** [comment]
Here is what I have prepared whilst waiting for your IPython/Python code to generate the chart, though it would be doing the same thing this new Rmd file would be doing

https://github.com/layik/kurdi/tree/w

**Comment by layik** [comment]
Supas kake gyan.

**Comment by 0xdolan** [comment]
ڕێزت هەیە دکتۆر گیان

**Pull request merged**
